name: Bug report
description: Create a bug report if anything's wrong with the website!
labels: [bug]
assignees:
- DuckMasterAl
body:
- type: input
  attributes:
    label: Website Page
    description: What's the website's page that has a bug?
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
  validations:
    required: false
- type: input
  attributes:
    label: What Happens?
    description: A clear and concise description of what the bug is.
  validations:
    required: true
- type: input
  attributes:
    label: What Should Happen?
    description: A clear and concise description of what you expected the website to do/display.
  validations:
    required: true
- type: input
  attributes:
    label: What Should Happen?
    description: A clear and concise description of what you expected the website to do/display.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context about the problem here.
  validations:
    required: false
