# ----------------------------------------------------------------
# DO NOT REMOVE THE TEXT BELOW IF YOU USE THIS IN YOUR OWN PROJECT
# ----------------------------------------------------------------
#
# Optimize Image GitHub Workflow | Optimizes images via tinypng.com
# Copyright (C) 2021 DuckMasterAl @ bduck.xyz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: Optimize Images
on:
  push:
    paths:
    - '**.png'
    - '**.jpg'
    - '**.jpeg'
    - '**.webp'
jobs:
  optimize-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get changed files
        id: files
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tinify

      - name: Call to API
        id: api
        run: python .github/script.py
        env:
          added_files: ${{ steps.files.outputs.added }}
          api_key: ${{ secrets.API_KEY }}

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Optimized Images"
          git push
