# Made by DuckMasterAl @ bduck.xyz

name: Optimize Images
on:
  push:
    paths:
    - '**.png'
    - '**.jpg'
    - '**.jpeg'
    - '**.webp'
jobs:
  optimize-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get changed files
        id: files
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tinify
      
      - name: Call to API
        id: api
        run: python .github/script.py
        env:
          added_files: ${{ steps.files.outputs.added }}
          api_key: ${{ secrets.API_KEY }}
          
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'github-actions' 
          git config --global user.email 'github-actions@github.com' 
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Optimized Images"
          git push
